# Generated by Django 3.0.5 on 2021-01-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetail',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, default='', max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('pan_number', models.CharField(max_length=12)),
                ('mobile_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=30)),
                ('photo', models.ImageField(default='', upload_to='user/image')),
                ('referral_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParmanentAddress',
            fields=[
                ('address_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('house_Number', models.CharField(max_length=5)),
                ('street', models.CharField(max_length=20)),
                ('village', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
                ('nationality', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_id', to='user.BasicDetail')),
            ],
        ),
    ]
