# Generated by Django 3.0.5 on 2021-01-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parmanentaddress',
            old_name='house_Number',
            new_name='house_number',
        ),
    ]
