# Generated by Django 3.0.5 on 2021-01-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210107_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetail',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='user/image'),
        ),
    ]
